import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() 
{
  const id=1;
  return (
    <>
      <Head>
        <title>Blogger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Blogs&nbsp;
            <code className={styles.code}></code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.grid}>
        <p> <Link href="/about">About</Link></p>
        <p> <Link href={`/blogs/${id}`}>First blog</Link></p>
        <p> <Link href="/users">Users</Link></p>
        <p> <Link href="/posts">Posts</Link></p>
        <p> <Link href="/posts-axios">Posts-Axios</Link></p>
        {/* <p> <Link href="/blogs/1">First blog</Link></p> */}
        
  
        </div>
      </main>
    </>
  )
}
